"""rename column updated at

Revision ID: 4f13c25ff14f
Revises: 9af00b8ea424
Create Date: 2024-11-29 11:03:59.109250

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f13c25ff14f'
down_revision: Union[str, None] = '9af00b8ea424'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('books', 'update_at')
    op.add_column('deleted_members', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('deleted_members', 'update_at')
    op.add_column('member_payments', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('member_payments', 'update_at')
    op.add_column('members', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('members', 'update_at')
    op.add_column('reviews', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('reviews', 'update_at')
    op.add_column('users', sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=True))
    op.drop_column('users', 'update_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'updated_at')
    op.add_column('reviews', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('reviews', 'updated_at')
    op.add_column('members', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('members', 'updated_at')
    op.add_column('member_payments', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('member_payments', 'updated_at')
    op.add_column('deleted_members', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('deleted_members', 'updated_at')
    op.add_column('books', sa.Column('update_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('books', 'updated_at')
    # ### end Alembic commands ###
