"""create members table

Revision ID: 68e3923232c0
Revises: a04d79012711
Create Date: 2024-11-25 15:24:02.678800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '68e3923232c0'
down_revision: Union[str, None] = 'a04d79012711'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('parentId', sa.BIGINT(), nullable=True),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('birth_year', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('relation_to_head', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('second_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fathers_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mosal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('profession', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line1', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address_line2', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('town', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('county', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('post_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telephone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mobile', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('newsletter', sa.Boolean(), nullable=False),
    sa.Column('directory', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members')
    # ### end Alembic commands ###
