"""add member payments and deleted members tables

Revision ID: 9af00b8ea424
Revises: f5a21c9f8f4a
Create Date: 2024-11-26 10:47:05.670870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9af00b8ea424'
down_revision: Union[str, None] = 'f5a21c9f8f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deleted_members',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BIGINT(), nullable=False),
    sa.Column('parentId', sa.BIGINT(), nullable=True),
    sa.Column('title', sa.VARCHAR(), nullable=True),
    sa.Column('first_name', sa.VARCHAR(), nullable=True),
    sa.Column('surname', sa.VARCHAR(), nullable=True),
    sa.Column('birth_year', sa.VARCHAR(), nullable=True),
    sa.Column('relation_to_head', sa.VARCHAR(), nullable=True),
    sa.Column('second_name', sa.VARCHAR(), nullable=True),
    sa.Column('fathers_name', sa.VARCHAR(), nullable=True),
    sa.Column('mosal', sa.VARCHAR(), nullable=True),
    sa.Column('profession', sa.VARCHAR(), nullable=True),
    sa.Column('address_line1', sa.VARCHAR(), nullable=True),
    sa.Column('address_line2', sa.VARCHAR(), nullable=True),
    sa.Column('town', sa.VARCHAR(), nullable=True),
    sa.Column('county', sa.VARCHAR(), nullable=True),
    sa.Column('post_code', sa.VARCHAR(), nullable=True),
    sa.Column('telephone', sa.VARCHAR(), nullable=True),
    sa.Column('mobile', sa.VARCHAR(), nullable=True),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('newsletter', sa.BOOLEAN(), nullable=False),
    sa.Column('directory', sa.BOOLEAN(), nullable=False),
    sa.Column('deleted_reason', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_payments',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('member_id', sa.BIGINT(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('receipt_no', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('is_cheque', sa.BOOLEAN(), nullable=False),
    sa.Column('cheque_no', sa.VARCHAR(), nullable=True),
    sa.Column('is_donation', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('update_at', postgresql.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('members', sa.Column('is_discontinued', sa.BOOLEAN(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'is_discontinued')
    op.drop_table('member_payments')
    op.drop_table('deleted_members')
    # ### end Alembic commands ###
