"""update column types

Revision ID: f5a21c9f8f4a
Revises: 9bb8f7358a6f
Create Date: 2024-11-25 16:38:55.526934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f5a21c9f8f4a'
down_revision: Union[str, None] = '9bb8f7358a6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'birth_year',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'relation_to_head',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'second_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'fathers_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'mosal',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'profession',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'address_line1',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'address_line2',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'town',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'county',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'post_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'telephone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'post_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'county',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'town',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'address_line2',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'address_line1',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'profession',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'mosal',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'fathers_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'second_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'relation_to_head',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'birth_year',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'surname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('members', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
